package com.edoe.orchestrator.entity;

public enum AuditEventType {
    // State transitions
    PROCESS_STARTED,
    STEP_TRANSITION,
    PROCESS_COMPLETED,
    PROCESS_FAILED,
    PROCESS_SUSPENDED,
    PROCESS_RESUMED,
    PROCESS_SCHEDULED,
    PROCESS_TIMER_FIRED,
    PROCESS_CANCELLED,
    PROCESS_STALLED,
    PROCESS_RETRIED,
    PROCESS_WOKEN,
    COMPENSATION_STEP,
    FORK_DISPATCHED,
    FORK_BRANCH_COMPLETED,
    FORK_JOINED,
    MULTI_INSTANCE_DISPATCHED,
    MULTI_INSTANCE_BRANCH_COMPLETED,
    MULTI_INSTANCE_JOINED,
    CHILD_PROCESS_STARTED,
    PARENT_RESUMED,
    PARENT_FAILED,

    // Command dispatched
    COMMAND_DISPATCHED,

    // Event received
    EVENT_RECEIVED,
    SIGNAL_RECEIVED
}
